name: Debug Test
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  debug:
    name: Run linting test
    runs-on: ubuntu-latest
    container:
      image: node:erbium
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Run ESLint test
        run: |
          npm install
          npm run test
